steps:
  # Build the Flask application image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/gem-enterprise-flask'
      - '-f'
      - 'Dockerfile.flask'
      - '.'

  # Push the Flask application image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/gem-enterprise-flask'

  # Deploy the Flask application to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'gem-enterprise-flask'
      - '--image'
      - 'gcr.io/$PROJECT_ID/gem-enterprise-flask'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

  # Build the Node.js media server image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/gem-enterprise-node'
      - '-f'
      - 'Dockerfile.node'
      - '.'

  # Push the Node.js media server image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/gem-enterprise-node'

  # Deploy the Node.js media server to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'gem-enterprise-node'
      - '--image'
      - 'gcr.io/$PROJECT_ID/gem-enterprise-node'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/gem-enterprise-flask'
  - 'gcr.io/$PROJECT_ID/gem-enterprise-node'
