# Stage 1: Build the environment
FROM node:20-slim as builder

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci

# Stage 2: Create the final image
FROM node:20-slim

WORKDIR /app

# Copy the installed dependencies from the builder stage
COPY --from=builder /app/node_modules ./node_modules

# Copy the application code
COPY server-media.js .

# Set the entrypoint
CMD ["node", "server-media.js"]
